name: example_flutter
description: Demonstrates how to use the sendsay plugin.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: ^2.17.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter

  sendsay:
    path: ../

  shared_preferences: ^2.2.3
  app_links: ^6.4.0
  intl: ^0.20.2
#  need constant version, because 4.0+ require higher minimal ios version
  firebase_core: 3.15.2

dev_dependencies:
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.3
  logger: ^2.6.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
